# Generated by Django 4.2.13 on 2024-05-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='expired_task',
            field=models.BooleanField(default=False),
        ),
    ]
